import { Node } from '../../../src/components/props'

export const frame: Node = {
  id: '1',
  label: 'イメージ',
  order: 10,
  type: 'frame',
  style: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 50,
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: 0,
    paddingLeft: 0,
  },
  children: [
    {
      id: '1',
      label: 'イメージ',
      order: 10,
      type: 'image',
      imageURL: 'https://www.nintendo.co.jp/switch/ampna/material/img/top/mv.jpg',
      imageSizeType: 'percentage',
      style: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
      },
      containerStyle: {
        display: 'flex',
        justifyContent: 'center',
      },
      linkType: 'internal',
      internalLink: null,
      externalLink: null,
    },
    {
      id: '2',
      label: 'イメージ',
      order: 10,
      type: 'image',
      imageURL: 'https://www.nintendo.co.jp/switch/ampna/material/img/top/mv.jpg',
      imageSizeType: 'percentage',
      style: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
      },
      containerStyle: {
        display: 'flex',
        justifyContent: 'center',
      },
      linkType: 'internal',
      internalLink: null,
      externalLink: null,
    },
    {
      id: '3',
      label: 'イメージ',
      order: 10,
      type: 'image',
      imageURL: 'https://www.nintendo.co.jp/switch/ampna/material/img/top/mv.jpg',
      imageSizeType: 'percentage',
      style: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
      },
      containerStyle: {
        display: 'flex',
        justifyContent: 'center',
      },
      linkType: 'internal',
      internalLink: null,
      externalLink: null,
    },
  ],
}
