import { Node } from '../../../src/components/props'

export const frame: Node = {
  id: '1',
  label: 'フレーム',
  order: 10,
  type: 'frame',
  thumbnailURL:
    'https://firebasestorage.googleapis.com/v0/b/funii-assist-dev.appspot.com/o/templates%2Fframe%402x.png?alt=media&token=9fd765d2-abad-4c05-b8f1-7b2acd83cb6a',
  styleMode: 'responsive',
  style: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 50,
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: 0,
    paddingLeft: 0,
  },
  styleTb: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    minHeight: 50,
    paddingTop: 100,
    paddingBottom: 10,
    paddingRight: 10,
    paddingLeft: 10,
  },
  styleMb: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 50,
    paddingTop: 100,
    paddingBottom: 20,
    paddingRight: 30,
    paddingLeft: 40,
  },
  children: [
    {
      id: '1',
      label: 'イメージ',
      order: 10,
      type: 'image',
      thumbnailURL:
        'https://firebasestorage.googleapis.com/v0/b/funii-assist-dev.appspot.com/o/templates%2Fimage%402x.png?alt=media&token=a99e979e-50a4-4171-a832-f41a791a5068',
      imageURL: 'https://www.nintendo.co.jp/switch/ampna/material/img/top/mv.jpg',
      imageSizeType: 'percentage',
      styleMode: 'common',
      style: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
      },
      styleMb: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 100,
        borderTopLeftRadius: 100,
        borderBottomRightRadius: 100,
        borderBottomLeftRadius: 100,
      },
      styleTb: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 30,
        borderTopLeftRadius: 30,
        borderBottomRightRadius: 30,
        borderBottomLeftRadius: 30,
      },
      containerStyle: {
        display: 'flex',
        justifyContent: 'center',
      },
      containerStyleMb: {
        display: 'flex',
        justifyContent: 'center',
      },
      containerStyleTb: {
        display: 'flex',
        justifyContent: 'center',
      },
      actions: [],
    },
    {
      id: '2',
      label: 'イメージ',
      order: 10,
      type: 'image',
      thumbnailURL:
        'https://firebasestorage.googleapis.com/v0/b/funii-assist-dev.appspot.com/o/templates%2Fimage%402x.png?alt=media&token=a99e979e-50a4-4171-a832-f41a791a5068',
      imageURL: 'https://www.nintendo.co.jp/switch/ampna/material/img/top/mv.jpg',
      imageSizeType: 'percentage',
      styleMode: 'common',
      style: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
      },
      styleMb: {
        width: 300,
        height: 300,
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 150,
        borderTopLeftRadius: 150,
        borderBottomRightRadius: 150,
        borderBottomLeftRadius: 150,
      },
      styleTb: {
        width: 300,
        height: 300,
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 150,
        borderTopLeftRadius: 150,
        borderBottomRightRadius: 150,
        borderBottomLeftRadius: 150,
      },
      containerStyle: {
        display: 'flex',
        justifyContent: 'center',
      },
      containerStyleMb: {
        display: 'flex',
        justifyContent: 'flex-end',
      },
      containerStyleTb: {
        display: 'flex',
        justifyContent: 'flex-end',
      },
      actions: [],
    },
    {
      id: '3',
      label: 'イメージ',
      order: 10,
      type: 'image',
      thumbnailURL:
        'https://firebasestorage.googleapis.com/v0/b/funii-assist-dev.appspot.com/o/templates%2Fimage%402x.png?alt=media&token=a99e979e-50a4-4171-a832-f41a791a5068',
      imageURL: 'https://www.nintendo.co.jp/switch/ampna/material/img/top/mv.jpg',
      imageSizeType: 'percentage',
      styleMode: 'common',
      style: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
      },
      styleTb: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
      },
      styleMb: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
      },
      containerStyle: {
        display: 'flex',
        justifyContent: 'center',
      },
      containerStyleTb: {
        display: 'flex',
        justifyContent: 'center',
      },
      containerStyleMb: {
        display: 'flex',
        justifyContent: 'center',
      },
      actions: [],
    },
  ],
}
