import { Node } from '../../../src/components/props'

export const frame: Node = {
  id: '1',
  label: 'イメージ',
  order: 10,
  type: 'frame',
  style: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 50,
    paddingTop: 0,
    paddingBottom: 0,
    paddingRight: 0,
    paddingLeft: 0,
  },
  children: [
    {
      id: '1',
      label: 'イメージ',
      order: 10,
      type: 'image',
      imageURL: 'https://www.nintendo.co.jp/switch/ampna/material/img/top/mv.jpg',
      imageSizeType: 'percentage',
      styleMode: 'common',
      style: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
      },
      styleMb: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 100,
        borderTopLeftRadius: 100,
        borderBottomRightRadius: 100,
        borderBottomLeftRadius: 100,
      },
      styleTb: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 30,
        borderTopLeftRadius: 30,
        borderBottomRightRadius: 30,
        borderBottomLeftRadius: 30,
      },
      containerStyle: {
        display: 'flex',
        justifyContent: 'center',
      },
      containerStyleMb: {
        display: 'flex',
        justifyContent: 'center',
      },
      containerStyleTb: {
        display: 'flex',
        justifyContent: 'center',
      },
      actions: [],
    },
    {
      id: '2',
      label: 'イメージ',
      order: 10,
      type: 'image',
      imageURL: 'https://www.nintendo.co.jp/switch/ampna/material/img/top/mv.jpg',
      imageSizeType: 'percentage',
      styleMode: 'common',
      style: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
      },
      styleMb: {
        width: 300,
        height: 300,
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 150,
        borderTopLeftRadius: 150,
        borderBottomRightRadius: 150,
        borderBottomLeftRadius: 150,
      },
      styleTb: {
        width: 300,
        height: 300,
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 150,
        borderTopLeftRadius: 150,
        borderBottomRightRadius: 150,
        borderBottomLeftRadius: 150,
      },
      containerStyle: {
        display: 'flex',
        justifyContent: 'center',
      },
      containerStyleMb: {
        display: 'flex',
        justifyContent: 'flex-end',
      },
      containerStyleTb: {
        display: 'flex',
        justifyContent: 'flex-end',
      },
      actions: [],
    },
    {
      id: '3',
      label: 'イメージ',
      order: 10,
      type: 'image',
      imageURL: 'https://www.nintendo.co.jp/switch/ampna/material/img/top/mv.jpg',
      imageSizeType: 'percentage',
      styleMode: 'common',
      style: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
      },
      styleTb: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
      },
      styleMb: {
        width: '100%',
        height: 'auto',
        objectFit: 'cover',
        overflow: 'hidden',
        borderTopRightRadius: 0,
        borderTopLeftRadius: 0,
        borderBottomRightRadius: 0,
        borderBottomLeftRadius: 0,
      },
      containerStyle: {
        display: 'flex',
        justifyContent: 'center',
      },
      containerStyleTb: {
        display: 'flex',
        justifyContent: 'center',
      },
      containerStyleMb: {
        display: 'flex',
        justifyContent: 'center',
      },
      actions: [],
    },
  ],
}
